spring:
  # security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 877156848028-1ccncpcu7as3m0tb786ofi46o76jk79o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile