# 서버
server:
  address: localhost
  port: 8080

spring:
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smallPeopleBlog?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: hongeuipyo
    password: Ghddmlvy93!

  # spring security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # 서블릿
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# 파일 업로드
itemImgLocation: /Users/hongeuipyo/Documents/upload/images
uploadPath: file:///Users/hongeuipyo/Documents/upload/images/

# 로깅
logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace

# VIP 할인 정책
vipDiscountPolicy:
  applyRole: SMALL_BUSINESS
  discountRate: 0.1